/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VtnAyuda.java
 *
 * Created on 06/12/2010, 06:35:34 PM
 */

package vista;

/**
 *
 * @author EDÚ
 */
public class VtnAyuda extends javax.swing.JDialog {

    /** Creates new form VtnAyuda */
    public VtnAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda para la ejecución");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Analizador Léxico\n\nPasos:\n\n1. Ejecutar el archivo Analizador_Lexico.jar\n2. Ingresar el valor a verificar en el campo de texto\n3. El programa mostrará automáticamente el LEXEMA y TOKEN de los datos ingresados\n   con su respectivo color según el lexema ingresado.\n4. El programa brindará la opción de:\n\n\t* Abrir documento     \t\tCtrl + A\n\t* Guardar documento\t\tCtrl + G\n\t* Nuevo documento\t\tCtrl + N\n\t* Imprimir documento\t\tCtrl + P\n\t* Salir del programa\t\tAlt  + F4\n\n5. El programa brinda la opción de:\n\n\t* Vista previa del documento\tCtrl + D\n\n6. El programa tambien brindará las opciones de Formato:\n\n\t* Copiar\t\tCtrl + C\n\t* Pegar\t\t\tCtrl + V\n\t* Cortar\t\tCtrl + X\n\n\nIntegrantes:\n\n\t* Eduardo Lima\n\t* Angel valdez\n\t* Carlos Vivanco\n\nMódulo:\n\n\tNoveno \"B\"  - Sistemas\n\nFecha:\n\n\t30-Noviembre-2010");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnAyuda dialog = new VtnAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
